from typing import Optional
import numpy as np

class BivariateKDE:
    def __new__(
        cls,
        x: np.ndarray,
        y: np.ndarray,
        weights: Optional[np.ndarray] = None,
    ) -> BivariateKDE: ...
    def len(self) -> int: ...
    def get_x(self) -> list[float]: ...
    def get_y(self) -> list[float]: ...
    def get_weights(self) -> list[float]: ...
    def __repr__(self) -> str: ...

def hello() -> str: ...

